# Minimal working yaml script for Travis CI

language: cpp

before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
## Gtest framework installation  
#- sudo apt-get install libgtest-dev cmake -y 
- sudo apt-get install libgtest-dev -y 
- sudo chmod 777 /usr/src/gtest
- cd /usr/src/gtest 
- cmake .
- make
- sudo cp *.a /usr/lib/
- cd "${TRAVIS_BUILD_DIR}"

  ## Yet another way. 
  #- sudo apt-get install -y libgtest-dev cmake
  #- sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  #- sudo tar xf release-1.7.0.tar.gz
  #- cd googletest-release-1.7.0
  #- sudo cmake -DBUILD_SHARED_LIBS=ON .
  #- sudo make
  #- sudo cp -a include/gtest /usr/include
  #- sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  #- cd "${TRAVIS_BUILD_DIR}"

 ## conan
#- sudo apt-get install python3-pip -y
- pip install --upgrade pip --user
- sudo pip install conan
- source ~/.profile
- conan
 

script:
 #- whereis cmake
 #- sudo /usr/local/cmake-3.12.4/bin/cmake .
- touch /home/travis/.conan/profiles/default
- chmod 777 /home/travis/.conan/profiles/default
- less /home/travis/.conan/profiles/default
- conan profile update settings.compiler.libcxx=libstdc++11 default
- conan install .
- cmake . -DHWALL=ON
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

deploy:
    provider: script
    skip_cleanup: true
    script:
    - curl -T homeworks-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uadv-dev-22:$BINTRAY_API_KEY "https://api.bintray.com/content/adv-dev-22/otus_cpp_hws/homeworks/$TRAVIS_BUILD_NUMBER/homeworks-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"




