# Minimal working yaml script for Travis CI

language: cpp

before_script:
#- sudo apt-get install libboost-test-dev -y
- sudo apt-get install libboost-all-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq

- sudo apt-get install -y software-properties-common
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt update
- sudo apt install g++-7 -y
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7 
- sudo update-alternatives --config gcc
- gcc --version
- g++ --version

## Gtest framework installation  
#- sudo apt-get install libgtest-dev cmake -y 
- sudo apt-get install libgtest-dev -y 
- sudo chmod 777 /usr/src/gtest
- cd /usr/src/gtest 
- cmake .
- make
- sudo cp *.a /usr/lib/
- cd "${TRAVIS_BUILD_DIR}"

  ## Yet another way. 
  #- sudo apt-get install -y libgtest-dev cmake
  #- sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  #- sudo tar xf release-1.7.0.tar.gz
  #- cd googletest-release-1.7.0
  #- sudo cmake -DBUILD_SHARED_LIBS=ON .
  #- sudo make
  #- sudo cp -a include/gtest /usr/include
  #- sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  #- cd "${TRAVIS_BUILD_DIR}"

## conan
- pip install --upgrade pip --user
- sudo pip install conan
- conan
 
# doxygen
- sudo apt-get install doxygen -y
- sudo apt-get install graphviz -y

script:
- conan install . -s compiler.libcxx=libstdc++11
- cmake . -DHWALL=ON
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen

deploy:
    provider: script
    skip_cleanup: true
    script:
    - curl -T homeworks-4.1.$TRAVIS_BUILD_NUMBER-Linux.deb -uadv-dev-22:$BINTRAY_API_KEY "https://api.bintray.com/content/adv-dev-22/otus_cpp_hws/homeworks/$TRAVIS_BUILD_NUMBER/homeworks-4.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
#    on:
#        branch: master
#    - provider: pages
#    skip_cleanup: true
#    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#    keep_history: true
#    on:
#        branch: master






