# Minimal working yaml script for Travis CI

language: cpp

before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
# Gtest framework installation  
##- sudo apt-get install libgtest-dev cmake -y 
#- sudo apt-get install libgtest-dev -y 
#- cmake --version
#- cd /usr/src/gtest 
#- sudo cmake .
#- sudo make
#- sudo cp *.a /usr/lib/
#- cd "${TRAVIS_BUILD_DIR}"

  ## Yet another way. 
  #- sudo apt-get install -y libgtest-dev cmake
  #- sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  #- sudo tar xf release-1.7.0.tar.gz
  #- cd googletest-release-1.7.0
  #- sudo cmake -DBUILD_SHARED_LIBS=ON .
  #- sudo make
  #- sudo cp -a include/gtest /usr/include
  #- sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  #- cd "${TRAVIS_BUILD_DIR}"

script:
- whereis cmake
- sudo /usr/local/cmake-3.12.4/bin/cmake .
- sudo cmake --build .
- sudo cmake --build . --target test
- sudo cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uadv-dev-22:$BINTRAY_API_KEY "https://api.bintray.com/content/adv-dev-22/otus-cpp-hw-01/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"




