# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake-3.12.4/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake-3.12.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/travis/build/adv-dev-22/otus_cpp_hw

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/travis/build/adv-dev-22/otus_cpp_hw

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake-3.12.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/cmake-3.12.4/bin/cpack --config ./CPackSourceConfig.cmake /home/travis/build/adv-dev-22/otus_cpp_hw/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake-3.12.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/cmake-3.12.4/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/cmake-3.12.4/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/adv-dev-22/otus_cpp_hw/CMakeFiles /home/travis/build/adv-dev-22/otus_cpp_hw/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/adv-dev-22/otus_cpp_hw/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_vers_gtest

# Build rule for target.
test_vers_gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_vers_gtest
.PHONY : test_vers_gtest

# fast build rule for target.
test_vers_gtest/fast:
	$(MAKE) -f 01/CMakeFiles/test_vers_gtest.dir/build.make 01/CMakeFiles/test_vers_gtest.dir/build
.PHONY : test_vers_gtest/fast

#=============================================================================
# Target rules for targets named test_vers_boost

# Build rule for target.
test_vers_boost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_vers_boost
.PHONY : test_vers_boost

# fast build rule for target.
test_vers_boost/fast:
	$(MAKE) -f 01/CMakeFiles/test_vers_boost.dir/build.make 01/CMakeFiles/test_vers_boost.dir/build
.PHONY : test_vers_boost/fast

#=============================================================================
# Target rules for targets named hw_version

# Build rule for target.
hw_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw_version
.PHONY : hw_version

# fast build rule for target.
hw_version/fast:
	$(MAKE) -f 01/CMakeFiles/hw_version.dir/build.make 01/CMakeFiles/hw_version.dir/build
.PHONY : hw_version/fast

#=============================================================================
# Target rules for targets named helloworld_cli

# Build rule for target.
helloworld_cli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld_cli
.PHONY : helloworld_cli

# fast build rule for target.
helloworld_cli/fast:
	$(MAKE) -f 01/CMakeFiles/helloworld_cli.dir/build.make 01/CMakeFiles/helloworld_cli.dir/build
.PHONY : helloworld_cli/fast

#=============================================================================
# Target rules for targets named ip_processor

# Build rule for target.
ip_processor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ip_processor
.PHONY : ip_processor

# fast build rule for target.
ip_processor/fast:
	$(MAKE) -f 02/CMakeFiles/ip_processor.dir/build.make 02/CMakeFiles/ip_processor.dir/build
.PHONY : ip_processor/fast

#=============================================================================
# Target rules for targets named custom_pair_exmpl_2

# Build rule for target.
custom_pair_exmpl_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 custom_pair_exmpl_2
.PHONY : custom_pair_exmpl_2

# fast build rule for target.
custom_pair_exmpl_2/fast:
	$(MAKE) -f 02_tuple/CMakeFiles/custom_pair_exmpl_2.dir/build.make 02_tuple/CMakeFiles/custom_pair_exmpl_2.dir/build
.PHONY : custom_pair_exmpl_2/fast

#=============================================================================
# Target rules for targets named cstm_tuple_exmpl

# Build rule for target.
cstm_tuple_exmpl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cstm_tuple_exmpl
.PHONY : cstm_tuple_exmpl

# fast build rule for target.
cstm_tuple_exmpl/fast:
	$(MAKE) -f 02_tuple/CMakeFiles/cstm_tuple_exmpl.dir/build.make 02_tuple/CMakeFiles/cstm_tuple_exmpl.dir/build
.PHONY : cstm_tuple_exmpl/fast

#=============================================================================
# Target rules for targets named custom_pair_exmpl

# Build rule for target.
custom_pair_exmpl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 custom_pair_exmpl
.PHONY : custom_pair_exmpl

# fast build rule for target.
custom_pair_exmpl/fast:
	$(MAKE) -f 02_tuple/CMakeFiles/custom_pair_exmpl.dir/build.make 02_tuple/CMakeFiles/custom_pair_exmpl.dir/build
.PHONY : custom_pair_exmpl/fast

#=============================================================================
# Target rules for targets named test_out_01

# Build rule for target.
test_out_01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_out_01
.PHONY : test_out_01

# fast build rule for target.
test_out_01/fast:
	$(MAKE) -f 03_ranges/CMakeFiles/test_out_01.dir/build.make 03_ranges/CMakeFiles/test_out_01.dir/build
.PHONY : test_out_01/fast

#=============================================================================
# Target rules for targets named ip_processor_rangesv3

# Build rule for target.
ip_processor_rangesv3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ip_processor_rangesv3
.PHONY : ip_processor_rangesv3

# fast build rule for target.
ip_processor_rangesv3/fast:
	$(MAKE) -f 03_ranges/CMakeFiles/ip_processor_rangesv3.dir/build.make 03_ranges/CMakeFiles/ip_processor_rangesv3.dir/build
.PHONY : ip_processor_rangesv3/fast

#=============================================================================
# Target rules for targets named test_reserve_allocator

# Build rule for target.
test_reserve_allocator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_reserve_allocator
.PHONY : test_reserve_allocator

# fast build rule for target.
test_reserve_allocator/fast:
	$(MAKE) -f 03_allocator/CMakeFiles/test_reserve_allocator.dir/build.make 03_allocator/CMakeFiles/test_reserve_allocator.dir/build
.PHONY : test_reserve_allocator/fast

#=============================================================================
# Target rules for targets named reserve_allocator

# Build rule for target.
reserve_allocator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reserve_allocator
.PHONY : reserve_allocator

# fast build rule for target.
reserve_allocator/fast:
	$(MAKE) -f 03_allocator/CMakeFiles/reserve_allocator.dir/build.make 03_allocator/CMakeFiles/reserve_allocator.dir/build
.PHONY : reserve_allocator/fast

#=============================================================================
# Target rules for targets named print_ip

# Build rule for target.
print_ip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 print_ip
.PHONY : print_ip

# fast build rule for target.
print_ip/fast:
	$(MAKE) -f 04_sfinae/CMakeFiles/print_ip.dir/build.make 04_sfinae/CMakeFiles/print_ip.dir/build
.PHONY : print_ip/fast

#=============================================================================
# Target rules for targets named test_print_ip

# Build rule for target.
test_print_ip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_print_ip
.PHONY : test_print_ip

# fast build rule for target.
test_print_ip/fast:
	$(MAKE) -f 04_sfinae/tests/CMakeFiles/test_print_ip.dir/build.make 04_sfinae/tests/CMakeFiles/test_print_ip.dir/build
.PHONY : test_print_ip/fast

#=============================================================================
# Target rules for targets named run_matrix

# Build rule for target.
run_matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_matrix
.PHONY : run_matrix

# fast build rule for target.
run_matrix/fast:
	$(MAKE) -f 06_matrix/CMakeFiles/run_matrix.dir/build.make 06_matrix/CMakeFiles/run_matrix.dir/build
.PHONY : run_matrix/fast

#=============================================================================
# Target rules for targets named test_inf_matrix

# Build rule for target.
test_inf_matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_inf_matrix
.PHONY : test_inf_matrix

# fast build rule for target.
test_inf_matrix/fast:
	$(MAKE) -f 06_matrix/tests/CMakeFiles/test_inf_matrix.dir/build.make 06_matrix/tests/CMakeFiles/test_inf_matrix.dir/build
.PHONY : test_inf_matrix/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... test"
	@echo "... test_vers_gtest"
	@echo "... test_vers_boost"
	@echo "... hw_version"
	@echo "... helloworld_cli"
	@echo "... ip_processor"
	@echo "... custom_pair_exmpl_2"
	@echo "... cstm_tuple_exmpl"
	@echo "... custom_pair_exmpl"
	@echo "... test_out_01"
	@echo "... ip_processor_rangesv3"
	@echo "... test_reserve_allocator"
	@echo "... reserve_allocator"
	@echo "... print_ip"
	@echo "... test_print_ip"
	@echo "... run_matrix"
	@echo "... test_inf_matrix"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

